package UssdWhitelabelPortal.whitelabel.enums;

public enum AuditType {
    DISABLE_USER("DISABLE_USER"),
    ENABLE_USER("ENABLE_USER"),
    DISABLE_DEVICE("DISABLE_DEVICE"),
    ENABLE_DEVICE("ENABLE_DEVICE"),
    RELEASE_DEVICE("RELEASE_DEVICE"),
    CREATE_PORTAL_USER("CREATE_PORTAL_USER"),
    EDIT_PORTAL_USER("EDIT_PORTAL_USER"),
    ENABLE_PORTAL_USER("ENABLE_PORTAL_USER"),
    DISABLE_PORTAL_USER("DISABLE_PORTAL_USER"),
    CREATE_BANK("CREATE_BANK"),
    EDIT_BANK("EDIT_BANK"),
    ENABLE_BANK("ENABLE_BANK"),
    DISABLE_BANK("DISABLE_BANK"),
    CREATE_BILLER("CREATE_BILLER"),
    EDIT_BILLER("EDIT_BILLER"),
    ENABLE_BILLER("ENABLE_BILLER"),
    DISABLE_BILLER("DISABLE_BILLER"),
    CREATE_CATEGORY("CREATE_CATEGORY"),
    EDIT_CATEGORY("EDIT_CATEGORY"),
    ENABLE_CATEGORY("ENABLE_CATEGORY"),
    DISABLE_CATEGORY("DISABLE_CATEGORY"),
    CREATE_PRODUCT("CREATE_PRODUCT"),
    EDIT_PRODUCT("EDIT_PRODUCT"),
    ENABLE_PRODUCT("ENABLE_PRODUCT"),
    DISABLE_PRODUCT("DISABLE_PRODUCT"),
    CREATE_ROLE("CREATE_ROLE"),
    EDIT_ROLE("EDIT_ROLE"),
    CREATE_MENU("CREATE_MENU"),
    EDIT_MENU("EDIT_MENU"),
    CREATE_CUSTOMER_LIMIT("CREATE_CUSTOMER_LIMIT"),
    EDIT_CUSTOMER_LIMIT("EDIT_CUSTOMER_LIMIT"),
    DELETE_CUSTOMER_LIMIT("DELETE_CUSTOMER_LIMIT"),
    EDIT_GLOBAL_SETTING("EDIT_GLOBAL_SETTING"),
    RESET_PASSWORD("RESET_PASSWORD"),
    RESET_PIN("RESET_PIN"),
    SECURITY_QUIZ_AND_ANSWER("SECURITY_QUIZ_AND_ANSWER"),
    EDIT_GLOBAL_AUTH_LIMIT("EDIT_GLOBAL_AUTH_LIMIT"),
    CREATE_BRANCH("CREATE_BRANCH"),
    EDIT_BRANCH("EDIT_BRANCH"),
    RELEASE_CUSTOMER("RELEASE_CUSTOMER"),
    CHANGE_PASSWORD("CHANGE_PASSWORD"),
    DELETE_PORTAL_USER("DELETE_PORTAL_USER"),
    PORTAL_USER_LOGIN("PORTAL_USER_LOGIN"),
    ENROLL_CUSTOMER("ENROLL_CUSTOMER"),
    ADD_ROLE_FUNCTION("ADD_ROLE_FUNCTION"),
    ENABLE_BRANCH("ENABLE_BRANCH"),
    DISABLE_BRANCH("DISABLE_BRANCH"),
    APPROVE_SERVICE_REQUEST("APPROVE_SERVICE_REQUEST"),
    DECLINE_SERVICE_REQUEST("DECLINE_SERVICE_REQUEST"),
    IN_PROGRESS_SERVICE_REQUEST("IN_PROGRESS_SERVICE_REQUEST"),
    UPDATE_PORTAL_PASSWORD_POLICY("UPDATE_PORTAL_PASSWORD_POLICY"),
    UPDATE_APP_PASSWORD_POLICY("UPDATE_APP_PASSWORD_POLICY"),
    EDIT_SETTING("EDIT_SETTING"),
    REMOVE_BILLER("REMOVE_BILLER"),
    ADD_BILLER("ADD_BILLER"),
    CHANGE_TRANSACTIONAL_STATUS("CHANGE_TRANSACTIONAL_STATUS"),
    RESET_COUNTER("RESET_COUNTER"),
    REMOVE_FILTERED_BANK("REMOVE_FILTERED_BANK"),
    ADD_FILTERED_BANK("ADD_FILTERED_BANK"),
    ADD_CONFIG_PROPERTY("ADD_CONFIG_PROPERTY"),
    EDIT_CONFIG_PROPERTY("EDIT_CONFIG_PROPERTY"),
    EDIT_GLOBAL_LIMIT("EDIT_GLOBAL_LIMIT"),
    ASSIGN_TRANSFER_ROUTE("ASSIGN_TRANSFER_ROUTE"),
    UNASSIGN_TRANSFER_ROUTE("UNASSIGN_TRANSFER_ROUTE"),
    ENABLE_TRANSFER_ROUTE("ENABLE_TRANSFER_ROUTE"),
    DISABLE_TRANSFER_ROUTE("DISABLE_TRANSFER_ROUTE"),
    CREATE_GLOBAL_LIMIT("CREATE_GLOBAL_LIMIT"),
    PORTAL_USER_LOGOUT("PORTAL_USER_LOGOUT"),
    CREATE_COUNTRY("CREATE_COUNTRY"),
    EDIT_COUNTRY("EDIT_COUNTRY"),
    CREATE_INSTITUTION("CREATE_INSTITUTION"),
    EDIT_INSTITUTION("EDIT_INSTITUTION"),
    EDIT_KYC_LEVEL_LIMIT("EDIT_KYC_LEVEL_LIMIT");

    public final String label;

    AuditType(String label) {
        this.label = label;
    }

    public static AuditType parse(String name) {

        try {
            return AuditType.valueOf(name);
        } catch (Exception ex) {
            return null;
        }

    }

    @Override
    public String toString() {
        return label;
    }
}